export default function Head() {
  return (
    <>
      <title>
        Adam Richardson - Fullstack Developer, Course Creator, Data Enthusiast
      </title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
